// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
	"github.com/gogf/gf/v2/database/gdb"
)

// userDao is the data access object for table user.
// You can define custom methods on it to extend its functionality as you wish.
type userDao struct {
	*internal.UserDao
}

var (
	// User is globally public accessible object for table user operations.
	User = userDao{
		internal.NewUserDao(),
	}
)

// Fill with you ideas below.

func Trans() (err error) {
	var db gdb.DB
	err = db.Transaction(context.TODO(), func(ctx context.Context, tx *gdb.TX) error {
		return nil
	})
	return
}